FUNCTION-POOL ZSDFG_0001.                   "MESSAGE-ID ..

* INCLUDE LZSDFG_0001D...                    " Local class definition

DATA : GT_DATA LIKE TABLE OF ZSDS0030 WITH HEADER LINE.
DATA : GT_HEADER LIKE TABLE OF ZSDS0030 WITH HEADER LINE.
DATA : GT_DATA_CAN LIKE TABLE OF ZSDS0031 WITH HEADER LINE.

DATA : GT_0032 LIKE TABLE OF ZSDS0032 WITH HEADER LINE.
DATA : GT_HEADER_2 LIKE TABLE OF ZSDS0032 WITH HEADER LINE.
DATA : GT_0033 LIKE TABLE OF ZSDS0033 WITH HEADER LINE.
DATA : GT_VBFA LIKE TABLE OF VBFA WITH HEADER LINE.
TYPES : BEGIN OF GTY_MSEG,
          VBELN_VL   LIKE ZSDS0030-VBELN_VL,
          MBLNR      LIKE MSEG-MBLNR,
          BUDAT_MKPF LIKE MSEG-BUDAT_MKPF,
          ERDAT      LIKE SY-DATUM,
          ERZET      LIKE SY-UZEIT,
        END OF GTY_MSEG.
DATA : GT_MSEG TYPE TABLE OF GTY_MSEG WITH HEADER LINE.
DATA : GT_MSEG_KEY TYPE TABLE OF GTY_MSEG WITH HEADER LINE.


DATA : GT_BDCDATA LIKE BDCDATA OCCURS 0 WITH HEADER LINE,
       GT_BDCMSG  TYPE TABLE OF BDCMSGCOLL WITH HEADER LINE.
DATA : GS_CTU_PARAMS TYPE CTU_PARAMS.
DATA : GV_MODE LIKE CTU_PARAMS-DISMODE.
DATA : GV_TIMES  TYPE I VALUE '10000',
       GV_SEC(3) TYPE P DECIMALS 1 VALUE '0.1'.
DATA : GT_VBAP LIKE TABLE OF VBAP WITH HEADER LINE.
DATA : GT_VBEP LIKE TABLE OF VBEP WITH HEADER LINE.
DATA : GT_ITEMS        TYPE  SHP_SLS_ITM_T,
       GS_ITEMS        TYPE  SHP_SLS_ITM,
       GT_ET_DLV_ITEMS TYPE  SHP_DLV_ITM_T,
       GS_ET_DLV_ITEMS TYPE  SHP_DLV_ITM,
       GT_ET_MESSAGES  TYPE  VBFS_T,
       GS_ET_MESSAGES  TYPE  VBFS.

*ZSD_BP_EVENT_RAISE
DATA: JOBGROUP     LIKE TBTCJOB-JOBGROUP VALUE 'INVOICE',
      JOBNAME      LIKE TBTCJOB-JOBNAME VALUE 'IV&X_&D_&T_&H',
      JOBNAME_GR   LIKE TBTCJOB-JOBNAME VALUE 'GR&X_&D_&T_&H',
      JOBCOUNT     LIKE TBTCJOB-JOBCOUNT,
      JOB_ACTIV,
      JOB_CLOSE,
      JOB_COUNT(3) TYPE P.
*********************************************************************
*** DEFINE
*********************************************************************
DEFINE _CLEAR.
  CLEAR : &1. CLEAR : &1[].
END-OF-DEFINITION.
DEFINE _RANGE.
  &1-SIGN   = &2.
  &1-OPTION = &3.
  &1-LOW    = &4.
  &1-HIGH   = &5.
  COLLECT &1. CLEAR &1.
END-OF-DEFINITION.
