FUNCTION-POOL ZSDFG_0004.                   "MESSAGE-ID ..

* INCLUDE LZSDFG_0004D...                    " Local class definition

DATA : BEGIN OF GS_ADDRESS_INFO,
         PARTNER     TYPE BUT020-PARTNER,
         NATION      TYPE ADRC-NATION,
         NAME1       TYPE ADRC-NAME1,
         NAME2       TYPE ADRC-NAME2,
         SEARCHTERM1 TYPE ADRC-SORT1,
         SEARCHTERM2 TYPE ADRC-SORT2,
         STREET      TYPE ADRC-STREET,
         HOUSE_NO    TYPE ADRC-HOUSE_NUM1,
         CITY        TYPE ADRC-CITY1,
         COUNTRY     TYPE ADRC-COUNTRY,
         POST_CODE1  TYPE ADRC-POST_CODE1,
         TRANSPZONE  TYPE ADRC-TRANSPZONE,
         REGION      TYPE ADRC-REGION,
         LANGU       TYPE ADRC-LANGU,
         TEL_NUMBER  TYPE ADRC-TEL_NUMBER,
         FAX_NUMBER  TYPE ADRC-FAX_NUMBER,
         MOBILE      TYPE ADR2-TEL_NUMBER,
         SMTP_ADDR   TYPE ADR6-SMTP_ADDR,
       END OF GS_ADDRESS_INFO.
DATA : GT_ADDRESS_INFO LIKE TABLE OF GS_ADDRESS_INFO.
