FUNCTION-POOL ZSDFG_0003.                   "MESSAGE-ID ..

CONSTANTS: GC_E(1)      VALUE 'E',
           GC_A(1)      VALUE 'A',
           GC_S(1)      VALUE 'S',
           GC_U(1)      VALUE 'U',
           GC_I(1)      VALUE 'I',
           GC_X(1)      VALUE 'X',
           GC_C(1)      VALUE 'C',
           GC_F(1)      VALUE 'F',

           GC_ME11(4)   VALUE 'ME11',
           GC_ME12(4)   VALUE 'ME12',
           GC_ME13(4)   VALUE 'ME13',

           GC_06(2)     VALUE '06',
           GC_331(3)    VALUE '331',
           GC_335(3)    VALUE '335',

           GC_MATNR(8)  VALUE 'Material',
           GC_LIFNR(6)  VALUE 'Vendor',
           GC_EKORG(14) VALUE 'Purchasing Org',
           GC_ESOKZ(31) VALUE 'Purchasing Info record Category',
           GC_DATAB(15) VALUE 'Valid-From Date',
           GC_DATBI(13) VALUE 'Valid To Date',
           GC_WERKS(5)  VALUE 'Plant',
           GC_EKGRP(16) VALUE 'Purchasing Group',
           GC_MWSKZ(8)  VALUE 'Tax Code',
           GC_BSTAE(13) VALUE 'Conf. Control'.

CONSTANTS: GC_MID   TYPE CHAR13 VALUE 'CALL_ZMMR0010',
           GC_SDATE TYPE STRING VALUE 'I_SDATE '.

DATA: GV_KNUMH      LIKE KONH-KNUMH,
      GV_BDC_MODE   TYPE CTU_MODE,
      GV_RESULT_TXT TYPE STRING,
      GV_LINECNT(2) TYPE N.

DATA: GS_DATA     TYPE ZMMS0070,

      GS_BAPIEINA TYPE BAPIEINA,
      GS_BAPIEINE TYPE BAPIEINE,
      GS_RETURN   TYPE BAPIRETURN.

DATA: BEGIN OF GS_MARC,
        MATNR TYPE MARC-MATNR,
        WERKS TYPE MARC-WERKS,
      END OF GS_MARC.

DATA: BEGIN OF GS_LFM1,
        LIFNR TYPE LFM1-LIFNR,
        EKORG TYPE LFM1-EKORG,
        PLIFZ TYPE LFM1-PLIFZ,
      END OF GS_LFM1.

DATA: BEGIN OF GS_EINE,
        MATNR TYPE EINA-MATNR,
        LIFNR TYPE EINA-LIFNR,
        INFNR TYPE EINE-INFNR,
        EKORG TYPE EINE-EKORG,
        ESOKZ TYPE EINE-ESOKZ,
        WERKS TYPE EINE-WERKS,
        NETPR TYPE EINE-NETPR,
        WAERS TYPE EINE-WAERS,
        PEINH TYPE EINE-PEINH,
        BPRME TYPE EINE-BPRME,
      END OF GS_EINE.

DATA: BEGIN OF GS_KONH,
        KNUMH TYPE KONH-KNUMH,
        DATAB TYPE KONH-DATAB,
        DATBI TYPE KONH-DATBI,
        KOPOS TYPE KONP-KOPOS,
        KBETR TYPE KONP-KBETR,
        KONWA TYPE KONP-KONWA,
        KPEIN TYPE KONP-KPEIN,
        KMEIN TYPE KONP-KMEIN,
      END OF GS_KONH.

DATA: BEGIN OF GS_A017,
        KAPPL TYPE A017-KAPPL,
        KSCHL TYPE A017-KSCHL,
        LIFNR TYPE A017-LIFNR,
        MATNR TYPE A017-MATNR,
        EKORG TYPE A017-EKORG,
        WERKS TYPE A017-WERKS,
        ESOKZ TYPE A017-ESOKZ,
        DATBI TYPE A017-DATBI,
        DATAB TYPE A017-DATAB,
        KNUMH TYPE A017-KNUMH,
      END OF GS_A017.

DATA: BEGIN OF GS_A018,
        KAPPL TYPE A018-KAPPL,
        KSCHL TYPE A018-KSCHL,
        LIFNR TYPE A018-LIFNR,
        MATNR TYPE A018-MATNR,
        EKORG TYPE A018-EKORG,
        ESOKZ TYPE A018-ESOKZ,
        DATBI TYPE A018-DATBI,
        DATAB TYPE A018-DATAB,
        KNUMH TYPE A018-KNUMH,
      END OF GS_A018.

* for check purchasing org.
DATA: BEGIN OF GS_EKORG,
        EKORG TYPE T024E-EKORG,
      END OF GS_EKORG.

* for check info record category.=
DATA : BEGIN OF GS_INFOCAT,
         ESOKZ TYPE EINE-ESOKZ,
       END OF GS_INFOCAT.

* for check plant
DATA : BEGIN OF GS_T001W,
         WERKS TYPE T001W-WERKS,
       END OF GS_T001W.

* for check purchasing Group
DATA : BEGIN OF GS_EKGRP,
         EKGRP TYPE T024-EKGRP,
       END OF GS_EKGRP.

* for check Tax Keys T007A
DATA : BEGIN OF GS_TAXCD,
         EKORG TYPE EKKO-EKORG,
         WERKS TYPE T001W-WERKS,
         MWSKZ TYPE T007A-MWSKZ,
         LAND1 TYPE T001W-LAND1,
         KALSM TYPE T007A-KALSM,
       END OF GS_TAXCD.

* for check Confirmation Control Keys
DATA : BEGIN OF GS_CONFKEY,
         BSTAE TYPE T163L-BSTAE,
       END OF GS_CONFKEY.



DATA: GT_DATA     LIKE TABLE OF GS_DATA,
      GT_MARC_C   LIKE TABLE OF GS_MARC,
      GT_LFM1_C   LIKE TABLE OF GS_LFM1,
      GT_MARC     LIKE TABLE OF GS_MARC,
      GT_LFM1     LIKE TABLE OF GS_LFM1,

      GT_EINE     LIKE TABLE OF GS_EINE,
      GT_KONH     LIKE TABLE OF GS_KONH,
      GT_A017     LIKE TABLE OF GS_A017,
      GT_A018     LIKE TABLE OF GS_A018,

      GT_BAPIEINA LIKE TABLE OF GS_BAPIEINA,
      GT_BAPIEINE LIKE TABLE OF GS_BAPIEINE,
      GT_RETURN   LIKE TABLE OF GS_RETURN,

      GT_MESSAGE  LIKE TABLE OF BDCMSGCOLL.

DATA : GT_EKORG   LIKE TABLE OF GS_EKORG.
DATA : GT_INFOCAT LIKE TABLE OF GS_INFOCAT.
DATA : GT_T001W   LIKE TABLE OF GS_T001W.
DATA : GT_EKGRP   LIKE TABLE OF GS_EKGRP.
DATA : GT_TAXCD   LIKE TABLE OF GS_TAXCD.
DATA : GT_CONFKEY LIKE TABLE OF GS_CONFKEY.

DATA : GV_TCODE   TYPE SY-TCODE.
