**&---------------------------------------------------------------------*
**& Include          ZSDR0060_SCR
**&---------------------------------------------------------------------*
TABLES : A908, SSCRFIELDS.


SELECTION-SCREEN BEGIN OF BLOCK B00 WITH FRAME TITLE TEXT-001.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: P_UPLO  TYPE C RADIOBUTTON GROUP RD1 DEFAULT 'X' USER-COMMAND RAD1.
SELECTION-SCREEN COMMENT 10(10) TEXT-002 FOR FIELD P_UPLO.
PARAMETERS: P_SEAR  TYPE C RADIOBUTTON GROUP RD1.
SELECTION-SCREEN COMMENT 40(12) TEXT-003 FOR FIELD P_SEAR.
SELECTION-SCREEN: END OF LINE.
SELECTION-SCREEN END OF BLOCK B00.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME.

PARAMETERS: P_TPLST LIKE A908-TPLST DEFAULT C_2011 MODIF ID GR2,        "Transportaion Planning Point
            P_DATAB LIKE A908-DATAB DEFAULT SY-DATLO MODIF ID GR3.      "Valid On
*            P_TYPE  TYPE C LENGTH 4 AS LISTBOX VISIBLE LENGTH 15 MODIF ID GR1. "Condition type

SELECT-OPTIONS S_TDLNR FOR A908-TDLNR MODIF ID GR3.  "Service Agent
SELECT-OPTIONS S_ADD02 FOR A908-ADD02 MODIF ID GR3.  "Trailer overall length
SELECT-OPTIONS S_KUNWE FOR A908-KUNWE MODIF ID GR3.  "Shipto

PARAMETERS: P_FILE  LIKE RLGRAP-FILENAME  DEFAULT C_XLS MODIF ID GR1.   "File Path

SELECTION-SCREEN END OF BLOCK B01.
