*&---------------------------------------------------------------------*
*& Include          ZSDR0200TOP
*&---------------------------------------------------------------------*
TABLES : SSCRFIELDS, VBAK.
*&---------------------------------------------------------------------*
*& INTERNAL TABLES
*&---------------------------------------------------------------------*

* Display
DATA: BEGIN OF GT_LIST OCCURS 0,
        EBELN     LIKE EKPO-EBELN,
        EBELP     LIKE EKPO-EBELP,
        VBELN     LIKE VBAP-VBELN,
        POSNR     LIKE VBAP-POSNR,
        MATNR     LIKE VBAP-MATNR,
        MATNR_TXT LIKE MAKT-MAKTX,
        KBETR_C   LIKE KONP-KBETR,
        KBETR_HQ  LIKE KONP-KBETR,
        KBETR_US  LIKE KONP-KBETR,
        KONWA     LIKE KONP-KONWA,
        BELNR     LIKE RBKP-BELNR,
        MBLNR     LIKE MSEG-MBLNR,
        ELIKZ     LIKE EKPO-ELIKZ,
        LOEKZ     LIKE EKPO-LOEKZ,
        VBELN_VL  LIKE LIKP-VBELN,
        ABGRU     LIKE VBAP-ABGRU,
        DISP,
        ICON(4),
        APPLYSO,
        APPLYPO,
        MESSAGE   TYPE BAPI_MSG,
        CELLSTYLE TYPE LVC_T_STYL,
        CELLCOLOR TYPE LVC_T_SCOL,
      END OF GT_LIST.

DATA: BEGIN OF GT_UPLOAD OCCURS 0,
        BSTNK LIKE VBAK-BSTNK,    "CUTOMER PO
        MATNR LIKE VBAP-MATNR,    "Material (SKU)
        KBETR LIKE KONP-KBETR,    "Sales Price
      END OF GT_UPLOAD.

*-- Sales Order
DATA: GS_ORDER_HEADER_IN  LIKE BAPISDHD1,
      GS_ORDER_HEADER_INX LIKE BAPISDHD1X.
DATA: GT_ORDER_ITEMS_IN       LIKE TABLE OF BAPISDITM WITH HEADER LINE,
      GT_ORDER_ITEMS_INX      LIKE TABLE OF BAPISDITMX WITH HEADER LINE,
      GT_ORDER_SCHEDULES_IN   LIKE TABLE OF BAPISCHDL  WITH HEADER LINE,
      GT_ORDER_SCHEDULES_INX  LIKE TABLE OF BAPISCHDLX WITH HEADER LINE,
      GT_ORDER_PARTNERS       LIKE TABLE OF BAPIPARNR  WITH HEADER LINE,
      GT_CHANGE_PARTNERS      LIKE TABLE OF BAPIPARNRC WITH HEADER LINE,
      GT_ORDER_CONDITIONS_IN  LIKE TABLE OF BAPICOND   WITH HEADER LINE,
      GT_ORDER_CONDITIONS_INX LIKE TABLE OF BAPICONDX  WITH HEADER LINE,
      GT_RETURN               LIKE TABLE OF BAPIRET2   WITH HEADER LINE,
      GT_EXTENSION            LIKE TABLE OF BAPIPAREX  WITH HEADER LINE,
      GT_TEXT                 TYPE STANDARD TABLE OF BAPISDTEXT WITH HEADER LINE.
DATA: GV_SALESDOCUMENT LIKE BAPIVBELN-VBELN,
      GS_HEADER_INX    LIKE BAPISDH1X.

*--PURCHASE ORDER
DATA : GS_POHEADER  LIKE BAPIMEPOHEADER,
       GS_POHEADERX LIKE BAPIMEPOHEADERX.

DATA : GT_POITEM       LIKE BAPIMEPOITEM     OCCURS 0 WITH HEADER LINE,
       GT_POITEMX      LIKE BAPIMEPOITEMX    OCCURS 0 WITH HEADER LINE,
       GT_POCOND       LIKE BAPIMEPOCOND OCCURS 0 WITH HEADER LINE,
       GT_POCONDX      LIKE BAPIMEPOCONDX OCCURS 0 WITH HEADER LINE.


DATA : GV_WAERS LIKE TCURC-WAERS.

*&---------------------------------------------------------------------*
*&  GLOBAL VARIABLE DECLARATION
*&---------------------------------------------------------------------*
DATA: OK_CODE TYPE SY-UCOMM.

*&---------------------------------------------------------------------*
*&  SELECTION-SCREEN.
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B0 WITH FRAME TITLE TEXT-T00.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 1.
PARAMETERS: P_DISP RADIOBUTTON GROUP R01 DEFAULT 'X' USER-COMMAND UC01.
SELECTION-SCREEN COMMENT 2(22) TEXT-S02 FOR FIELD P_DISP.
SELECTION-SCREEN POSITION 31.
PARAMETERS: P_UPLOAD RADIOBUTTON GROUP R01.
SELECTION-SCREEN COMMENT 32(20) TEXT-S01 FOR FIELD P_UPLOAD.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B0.


SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.

PARAMETERS : P_VKORG LIKE VBAK-VKORG  MEMORY ID VKO.
SELECT-OPTIONS : S_BSTNK FOR VBAK-BSTNK MODIF ID M1 OBLIGATORY.
PARAMETERS : P_FILE  LIKE RLGRAP-FILENAME DEFAULT 'C:\' MODIF ID M2.

SELECTION-SCREEN END OF BLOCK B1.
SELECTION-SCREEN FUNCTION KEY 1.

*********************************************************************
*** DEFINE
*********************************************************************
DEFINE _CLEAR.
  CLEAR : &1. CLEAR : &1[].
END-OF-DEFINITION.
DEFINE _RANGE.
  &1-SIGN   = &2.
  &1-OPTION = &3.
  &1-LOW    = &4.
  &1-HIGH   = &5.
  COLLECT &1. CLEAR &1.
END-OF-DEFINITION.
