*&---------------------------------------------------------------------*
*& Include          ZSDR0090_SCR
*&---------------------------------------------------------------------*
TABLES : RKPF, RESB, SSCRFIELDS.

SELECTION-SCREEN BEGIN OF BLOCK B00 WITH FRAME TITLE TEXT-001.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: P_UPLO  TYPE C RADIOBUTTON GROUP RD1 DEFAULT 'X' USER-COMMAND RAD1.
SELECTION-SCREEN COMMENT 10(10) TEXT-002 FOR FIELD P_UPLO.
PARAMETERS: P_SEAR  TYPE C RADIOBUTTON GROUP RD1.
SELECTION-SCREEN COMMENT 40(12) TEXT-003 FOR FIELD P_SEAR.
SELECTION-SCREEN: END OF LINE.
SELECTION-SCREEN END OF BLOCK B00.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME.

PARAMETERS: P_BWART TYPE RKPF-BWART DEFAULT '311',   "Movement type
            P_WERKS TYPE RESB-WERKS,   "Plant
            P_LGORT TYPE RESB-LGORT.   "From Storage Location

SELECT-OPTIONS: S_UMLGO FOR RESB-UMLGO MODIF ID GR2, "To Storage Location
                S_BDTER FOR RESB-BDTER MODIF ID GR2. "Requirements Date

PARAMETERS: P_FILE  TYPE TEXT1024 MODIF ID GR1. "File upload

SELECTION-SCREEN END OF BLOCK B01.

SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-005.
PARAMETERS: P_ALL RADIOBUTTON GROUP RD2 DEFAULT 'X' USER-COMMAND RAD2 MODIF ID GR2.
PARAMETERS: P_NOT RADIOBUTTON GROUP RD2 MODIF ID GR2.
PARAMETERS: P_COM RADIOBUTTON GROUP RD2 MODIF ID GR2.
SELECTION-SCREEN END OF BLOCK B02.
