*&---------------------------------------------------------------------*
*& Include          ZSDR0010TOP
*&---------------------------------------------------------------------*

DATA : RA_NORM  TYPE C VALUE 'X',
       RA_MDDP  TYPE C,
       RA_INIT  TYPE C,
       RA_MANU  TYPE C,
       RA_SALES TYPE C.

DATA: OK_CODE TYPE SY-UCOMM.

DATA : GV_DATE TYPE SYDATUM,
       GV_DATE2 TYPE SYDATUM.

DATA : GV_TITLE LIKE SOOD1-OBJDES,
       GV_TEXT1 LIKE SOLI-LINE,
       GV_TEXT2 LIKE SOLI-LINE,
       GV_TEXT3 LIKE SOLI-LINE,
       GV_TEXT4 LIKE SOLI-LINE,
       GV_TEXT5 LIKE SOLI-LINE,
       GV_TEXT6 LIKE SOLI-LINE,
       GV_TEXT7 LIKE SOLI-LINE.

DATA : BEGIN OF GS_STATUS,
         STAT_01  TYPE ICON_D,  "Margin
         STAT_01D TYPE CHAR10,
         STAT_02  TYPE ICON_D,
         STAT_02D TYPE CHAR10,
         STAT_03  TYPE ICON_D,
         STAT_03D TYPE CHAR10,
         STAT_04  TYPE ICON_D,
         STAT_04D TYPE CHAR10,
         STAT_05  TYPE ICON_D,
         STAT_05D TYPE CHAR10,
       END OF GS_STATUS.

DATA : GV_INTERCOM_FG TYPE C,
       GV_ZTYPE.

DATA : BEGIN OF GS_0021,
         ZSTART          TYPE ZSDT0021-ZSTART,
         ZMARGIN         TYPE ZSDT0021-ZMARGIN,
         ZMARGIN_DATE    TYPE ZSDT0021-ZMARGIN_DATE,
         ZHQCAL          TYPE ZSDT0021-ZHQCAL,
         ZHQCAL_DATE     TYPE ZSDT0021-ZHQCAL_DATE,
         ZINTERCAL_I     TYPE ZSDT0021-ZINTERCAL_I,
         ZINTERCAL_IDATE TYPE ZSDT0021-ZINTERCAL_IDATE,
         ZINTERCAL_S     TYPE ZSDT0021-ZINTERCAL_S,
         ZINTERCAL_SDATE TYPE ZSDT0021-ZINTERCAL_SDATE,
         ZINTERFACE      TYPE ZSDT0021-ZINTERFACE,
         ZINTERFACE_DATE TYPE ZSDT0021-ZINTERFACE_DATE,
         ZCONFIRM        TYPE ZSDT0021-ZCONFIRM,
         ZCONFIRM_DATE   TYPE ZSDT0021-ZCONFIRM_DATE,
       END OF GS_0021.
DATA GT_0021 LIKE TABLE OF GS_0021.


DATA : GT_RETURNTAB TYPE STANDARD TABLE OF DDSHRETVAL,
       GS_RETURNTAB LIKE LINE OF GT_RETURNTAB.
