*&---------------------------------------------------------------------*
*& Include          ZSDR0150TOP
*&---------------------------------------------------------------------*
TABLES : VBRK.

*&---------------------------------------------------------------------*
*& INTERNAL TABLES
*&---------------------------------------------------------------------*

* Display
DATA: BEGIN OF GT_LIST OCCURS 0,
        VBELN_VF     LIKE VBRK-VBELN, "billing
        POSNR_VF     LIKE VBRP-POSNR, "billing item
        VBELN_VL     LIKE LIPS-VBELN, "Delivery
        POSNR_VL     LIKE LIPS-POSNR, "Delivery item
        VBELN        LIKE VBAP-VBELN, "SO
        POSNR        LIKE VBAP-POSNR, "SO ITEM
        BSTKD        LIKE VBKD-BSTKD, "CUST REF
        POSEX        LIKE VBAP-POSEX, "CUST REF ITEM
        ZZKOINV      LIKE VBRK-ZZKOINV, "KO INVOICE
        AUART        LIKE VBAK-AUART,
        VBELN2       LIKE VBAP-VBELN, "NEW SO
        POSNR2       LIKE VBAP-POSNR, "NEW SO ITEM
        VBELN_VF2    LIKE VBRP-VBELN, "NEW BILLING
        POSNR_VF2    LIKE VBRP-POSNR, "NEW BILLING ITEM
        KUNAG        LIKE VBRK-KUNAG, "SOLD TO
        KUNAG_TXT    LIKE BUT000-NAME_ORG1,
        LIFNR        LIKE VBPA-LIFNR, "GOODS SUPPLIER
        LIFNR_TXT    LIKE BUT000-NAME_ORG1,
        KUNWE        LIKE VBPA-KUNNR, "SHIP-TO
        KUNWE_TXT    LIKE BUT000-NAME_ORG1, "SHIP-TO NAME
        BWTAR        LIKE LIPS-BWTAR, "VALUATION TYPE
        MATNR        LIKE VBRP-MATNR, "SKU
        ARKTX        LIKE VBRP-ARKTX, "SKU Description
        FKIMG        LIKE VBRP-FKIMG, "QTY
        VRKME        LIKE VBRP-VRKME, "UNIT
        NETWR1       LIKE VBRP-NETWR, "BILLING AMOUNT
        CMPRE        LIKE VBRP-CMPRE, "BILLING UNIT PRICE
        KBETR_AD     LIKE VBRP-CMPRE, "Adjust unit price
        NETWR_AD     LIKE VBRP-CMPRE, "Adjust amount
        NETWR2       LIKE VBRP-NETWR, "SPECIAL amount
        KBETR2       LIKE VBRP-CMPRE, "SPECIAL unit price
        WAERK        LIKE VBRK-WAERK, "currency
        VKORG        LIKE VBRK-VKORG,
        VTWEG        LIKE VBRK-VTWEG,
        WERKS        LIKE VBRP-WERKS,
        KPEIN        LIKE PRCD_ELEMENTS-KPEIN,
        KMEIN        LIKE PRCD_ELEMENTS-KMEIN,
        BUKRS        LIKE VBRK-BUKRS,
        WADAT_IST    LIKE LIKP-WADAT_IST,
        FKDAT        LIKE VBRK-FKDAT,
        ICON(4),
        SEND,
        ZUPDATE,
        ZMARGIN      LIKE ZSDT0140-ZMARGIN,
        MESSAGE(100),
        CELLSTYLE    TYPE LVC_T_STYL,
        CELLCOLOR    TYPE LVC_T_SCOL,
      END OF GT_LIST.

*&---------------------------------------------------------------------*
*&  GLOBAL VARIABLE DECLARATION
*&---------------------------------------------------------------------*
DATA: OK_CODE TYPE SY-UCOMM.

DATA : GV_TIMES  TYPE I VALUE '200',
       GV_SEC(3) TYPE P DECIMALS 1 VALUE '0.1'.

DATA : GV_SUCCESS(5),
       GV_FAILURE(5).

DATA: GV_IF_TSP    TYPE TIMESTAMPL.
* API
DATA: GV_API_D TYPE STRING VALUE 'http://10.65.1.20:9500/api/v2/b_sp_unit_price_so_list', "개발
      GV_API_Q TYPE STRING VALUE 'http://10.65.1.20:9000/api/v2/b_sp_unit_price_so_list', "테스트
      GV_API_P TYPE STRING VALUE 'http://10.65.1.20:8000/api/v2/b_sp_unit_price_so_list', "운영
      GV_API   TYPE STRING.

CONSTANTS: GC_CON_TYP TYPE STRING VALUE 'application/json; charset=UTF-8',
           GC_API_KEY TYPE STRING VALUE 'x-zinus-api-key',
           GC_API_VAL TYPE STRING VALUE '6b33645a-1064-495b-8a33-3ab45134a562'.
DATA: GV_IF_STATUS TYPE ZMMT0010-STATUS,
      GV_IF_MSG    TYPE ZMMT0010-MSG.

DATA: BEGIN OF GS_DATA.
    INCLUDE STRUCTURE ZSDS0080.
DATA: END OF GS_DATA.
DATA: GT_DATA LIKE TABLE OF GS_DATA.

DATA: BEGIN OF GS_RETURN.
    INCLUDE STRUCTURE ZMMS0140.
DATA: END OF GS_RETURN.

*-- Sales Order
DATA: GS_ORDER_HEADER_IN  LIKE BAPISDHD1,
      GS_ORDER_HEADER_INX LIKE BAPISDHD1X.
DATA: GT_ORDER_ITEMS_IN       LIKE TABLE OF BAPISDITM WITH HEADER LINE,
      GT_ORDER_ITEMS_INX      LIKE TABLE OF BAPISDITMX WITH HEADER LINE,
      GT_ORDER_SCHEDULES_IN   LIKE TABLE OF BAPISCHDL  WITH HEADER LINE,
      GT_ORDER_SCHEDULES_INX  LIKE TABLE OF BAPISCHDLX WITH HEADER LINE,
      GT_ORDER_PARTNERS       LIKE TABLE OF BAPIPARNR  WITH HEADER LINE,
      GT_ORDER_CONDITIONS_IN  LIKE TABLE OF BAPICOND   WITH HEADER LINE,
      GT_ORDER_CONDITIONS_INX LIKE TABLE OF BAPICONDX  WITH HEADER LINE,
      GT_RETURN               LIKE TABLE OF BAPIRET2   WITH HEADER LINE,
      GT_TEXT                 TYPE STANDARD TABLE OF BAPISDTEXT WITH HEADER LINE.
DATA: GV_POSNR         TYPE POSNR_VA,
      GV_SALESDOCUMENT LIKE BAPIVBELN-VBELN.

DATA : GV_WAERS LIKE TCURC-WAERS,

       BEGIN OF GT_CREDIT OCCURS 0,
         VBELN_VF LIKE VBRK-VBELN,
         POSNR_VF LIKE VBRP-POSNR, "billing item
         VBELN    LIKE VBAP-VBELN,
         POSNR    LIKE VBAP-POSNR,
         VBELN2   LIKE VBAP-VBELN,
         POSNR2   LIKE VBAP-POSNR,
         VKORG    LIKE VBRK-VKORG,
         VTWEG    LIKE VBRK-VTWEG,
         KUNAG    LIKE VBRK-KUNAG, "SOLD TO
         KUNWE    LIKE VBPA-KUNNR, "SHIP-TO
         LIFNR    LIKE VBPA-LIFNR, "GOODS SUPPLIER
         WERKS    LIKE VBRP-WERKS,
         ZZKOINV  LIKE VBRK-ZZKOINV, "KO INVOICE
         BWTAR    LIKE LIPS-BWTAR, "VALUATION TYPE
         MATNR    LIKE VBAP-MATNR,
         FKIMG    LIKE VBRP-FKIMG, "QTY
         KBETR_AD LIKE VBRP-CMPRE, "
         VRKME    LIKE VBRP-VRKME,
         BSTKD    LIKE VBKD-BSTKD,
         NETWR_AD LIKE VBRP-NETWR,
         WAERK    LIKE VBRK-WAERK, "currency
         FKDAT    LIKE VBRK-FKDAT,
       END OF GT_CREDIT,
       GT_DEBIT LIKE TABLE OF GT_CREDIT WITH HEADER LINE.

*BDC
DATA : GT_BDCDATA LIKE BDCDATA OCCURS 0 WITH HEADER LINE,
       GT_BDCMSG  TYPE TABLE OF BDCMSGCOLL WITH HEADER LINE.
DATA : GS_CTU_PARAMS TYPE CTU_PARAMS.


*&---------------------------------------------------------------------*
*&  SELECTION-SCREEN.
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B0 WITH FRAME TITLE TEXT-T00.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 1.
PARAMETERS: P_CRE RADIOBUTTON GROUP R01 DEFAULT 'X' USER-COMMAND UC01.
SELECTION-SCREEN COMMENT 2(30) TEXT-R01 FOR FIELD P_CRE.
SELECTION-SCREEN POSITION 34.
PARAMETERS: P_DISP RADIOBUTTON GROUP R01.
SELECTION-SCREEN COMMENT 35(20) TEXT-R02 FOR FIELD P_DISP.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B0.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-T01.

SELECT-OPTIONS : S_FKDAT FOR VBRK-FKDAT,
                 S_VKORG FOR VBRK-VKORG NO-EXTENSION NO INTERVALS,
                 S_VTWEG FOR VBRK-VTWEG NO-EXTENSION NO INTERVALS,
                 S_KUNAG FOR VBRK-KUNAG NO-EXTENSION NO INTERVALS,
                 S_KOINV FOR VBRK-ZZKOINV MODIF ID Z02.

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME.

PARAMETERS : P_MARGIN TYPE ZE_MARGIN MODIF ID Z01.

SELECTION-SCREEN END OF BLOCK B2.

*********************************************************************
*** DEFINE
*********************************************************************
DEFINE _CLEAR.
  CLEAR : &1. CLEAR : &1[].
END-OF-DEFINITION.

DEFINE _RANGE.
  &1-SIGN   = &2.
  &1-OPTION = &3.
  &1-LOW    = &4.
  &1-HIGH   = &5.
  COLLECT &1. CLEAR &1.
END-OF-DEFINITION.
